name: 'Cache gradle dependencies'
description: 'Caches the gradle dependencies'

runs:
  using: 'composite'
  steps:
    - name: Cache Gradle dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/gradle/libs.versions.toml') }}
        restore-keys: |
          ${{ runner.os }}-gradle-caches-
