name: 'Read current version'
description: 'Reads current version from the version.properties file and sets it to the current_version environment variable'

inputs:
  filename:
    description: 'The name of the file to read the version from'
    required: true
    default: 'versions.properties'

outputs:
  current_version:
    description: 'The current version read from the file'
    value: ${{ steps.read_version.outputs.current_version }}

runs:
  using: 'composite'
  steps:
    - name: Read version
      id: read_version
      shell: bash
      env:
        CURRENT_VERSION_FILENAME: ${{ inputs.filename }}
      run: |
        version=$(grep 'version=' "$CURRENT_VERSION_FILENAME" | cut -d'=' -f2)
        echo "current_version=$version" >> $GITHUB_ENV
        echo "current_version=$version" >> $GITHUB_OUTPUT
        echo "current_version=$version"
